In [8]:
## calcul ALG2
import math
import copy 
import numpy as np 
def list_Into_tuple(liste):
    for i in range(len(liste)):
        liste[i]=tuple(liste[i])
    return tuple(liste)
def tuple_into_list(tupl):
    res=[]
    for i in tupl:
        res.append(list(i))
    return res
def affiche_matrice(matrice):
    for i in matrice:
        print(i)
        
def scalaire_usuel(X,Y):
    res=[]
    for i,j in zip(X,Y):
        res.append(i*j)
    return res
def det_sarus(matrice):
    res=tuple_into_list(matrice)
    if len(res)==1:
         return 'pas une matrice'
    elif len(res)==2:
        determinant = res[0][0]*res[1][1] - res[1][0]*res[0][1]
    elif len(res)==3:
        determinant = ((res[0][0]*res[1][1]*res[2][2])+(res[1][0]*res[2][1]*res[0][2])+(res[2][0]*res[0][1]*res[1][2]))-((res[0][2]*res[1][1]*res[2][0])+(res[0][0]*res[2][1]*res[1][2])+(res[2][2]*res[0][1]*res[1][0])) 
    if determinant!=0: 
        return determinant
    else:
        return determinant
    
def transposée(matrice):
    enter=tuple_into_list(matrice)
    res=copy.deepcopy(enter)
    for j in range(len(enter)):
        for k in range(len(enter)):
            res[j][k]=enter[k][j]
    return list_Into_tuple(res)
            
    
def commatrice(matrice) :
    liste=tuple_into_list(matrice)
    res=copy.deepcopy(liste)
    for i in range(len(liste)):
            for k in range(len(liste)):
                tmp=copy.deepcopy(liste)
                for j in range(len(liste)):
                    tmp[j].pop(k)
                tmp.pop(i)
                res[i][k]=(-1)**(i+k)*det_sarus(tmp)
                del(tmp) 
    return list_Into_tuple(res)
def matrice_inverse(matrice):
    print(f"le determinant est{det_sarus(matrice)}")
    affiche_matrice(transposée(commatrice(matrice)))
    
         
            
    
        
""""
A1= ((1,2,3),
     (4,5,6),
     (7,8,9))
A=transposée(A1)
affiche_matrice(A)
B=commatrice(A1)
affiche_matrice(B)
M=((1,2,3),(0,0,1),(0,1,2))
M1=(commatrice(M))
M2=transposée(M1)
matrice_inverse(M)
"""
A = np.array([[2,-2,3],[-5,2,9],[0,1,3]])

print(f"la matrice A: \n {A}")
B=np.sum(A)
print(f"le resultat de np.sum \n {B}")
C = np.sum(A, axis=0)
print(f"le resultat de np.sum avec axes = 0 \n {C}")
print(f"resultat: \n {B+C}")


la matrice A: 
 [[ 2 -2  3]
 [-5  2  9]
 [ 0  1  3]]
le resultat de np.sum 
 13
le resultat de np.sum avec axes = 0 
 [-3  1 15]
resultat: 
 [10 14 28]
