In [3]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.random.random(size=(3,3))

array([[0.03494454, 0.10927987, 0.06716898],
       [0.72583   , 0.94349615, 0.30957571],
       [0.93038913, 0.58742161, 0.21423714]])

In [30]:
myArray = np.random.rand(5)
print(myArray)

myArray_multiDim = np.random.rand(9).reshape(3,3)
print(myArray_multiDim)


[0.01333007 0.41402568 0.95097232 0.67839486 0.53317967]
[[0.05644213 0.51491345 0.16674773]
 [0.74786098 0.15446108 0.04522708]
 [0.16215897 0.73687242 0.12797542]]


In [46]:
print(myArray_multiDim[1:2][0])

[0.74786098 0.15446108 0.04522708]


## Fonction mathématiques

In [52]:
array = np.arange(10).reshape(5,2)
print(array)
print(np.cos(array))
np.exp(array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 1.          0.54030231]
 [-0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219]
 [ 0.96017029  0.75390225]
 [-0.14550003 -0.91113026]]


array([[1.00000000e+00, 2.71828183e+00],
       [7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03]])

In [58]:
print(array.mean())
print(np.mean(array))
print(np.var(array))

4.5
4.5
8.25


## Calcul matricielle

In [73]:
A = np.arange(16).reshape((4,4))
print(A)

B = np.random.rand(16).reshape((4,4))
print(B)

print(A*B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0.04119727 0.14896077 0.3951336  0.78200635]
 [0.95210931 0.84823551 0.49021788 0.41750148]
 [0.00750059 0.64241795 0.52100274 0.39241901]
 [0.73758531 0.30364573 0.51201007 0.22012566]]
[[0.         0.14896077 0.7902672  2.34601906]
 [3.80843725 4.24117755 2.94130728 2.92251038]
 [0.06000468 5.78176153 5.21002741 4.31660908]
 [8.85102366 3.94739454 7.16814095 3.30188492]]


In [74]:
#Produit Matricielle
A.dot(B)

array([[ 3.1798664 ,  3.04400861,  3.06825356,  1.86271648],
       [10.13343627, 10.81704847, 10.74171071,  9.11092651],
       [17.08700614, 18.59008834, 18.41516786, 16.35913653],
       [24.04057601, 26.3631282 , 26.088625  , 23.60734655]])

In [75]:
#Transposé
A.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [76]:
#Matrice inversible
np.linalg.inv(np.random.rand(16).reshape(4,4))

array([[-0.08654701,  1.27685947,  0.5151504 , -0.63747689],
       [-2.20274202, -1.65450541,  1.20111807,  3.59000201],
       [ 2.04711245,  1.21988793, -2.72364092, -1.01526629],
       [ 2.23849999,  0.54574861,  0.78975079, -3.41974884]])